title: <p align="center"> Ganga Gowthami </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="file:///D:/Resume%20-%20Gowthami.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gowthami-g-b8242421b/">LinkedIn</a> |
  <a href="https://github.com/GangaGowthami">GitHub</a>
  
  <br>   
  I'm working as a Report Developer on PowerBI and SQL.
  Also Hands-on experience in reporting services, Power BI and SSRS using MS SQL server.
  Working in Antrix Technology India Pvt Ltd since last 4 years.
  <br>
  </p>



theme: jekyll-theme-minimal
